# One small program holding a sizeable instance of EVERY feature the sealed
# trimming compiler must get right.
#
#     julia features.jl source [K S N U P V] > work/features.jl
#
# WHY IT EXISTS. The routing model is the only program that exercised all of
# these together, and it costs 22 minutes a build — too slow to work on. Each
# feature below is here because something measured needed it, not because it
# seemed representative:
#
#   F1  an abstract type IS the union of its concretes            sealed_patch2
#   F2  dynamic dispatch left above the split threshold           sealed_patch3
#   F3  a record of N optional fields, so 2^N at its constructor  sealed_patch8
#   F4  a binary operator over a wide union, so U^2 at the call   DESIGN.md §8a: `_apply` 53^2
#   F5  a parametric constructor over P union parameters, V^P     DESIGN.md §8a: `ISequentialEvent` 5^6
#   F6  a STEM instance: a method compiled at its own abstract
#       signature, which the drain filter must keep               sealed_patch3
#   F7  generated per-type methods, one instance per kind         sealed_patch4
#   F8  keyword arguments                                         a fix routed into the
#                                                                 keyword body and took
#                                                                 routing 9 -> 16 errors
#   F9  run-time string parsing and formatted output              sealed_patch4, sealed_patch5
#
# `warm()` mirrors `main` phase by phase, as a real build entry must: the warm
# run populates the instance table and `main` is compiled cold.
#
# BOTH SOURCES ARE NEEDED, AND THIS PROGRAM EXERCISES BOTH. A trace-seeded
# compiler takes its static call graph from `CodeInstance.edges` and must
# OBSERVE the rest, because above `max_union_splitting` (4 in stock Julia)
# inference leaves the call dynamic and records no edge at all. Measured on the
# default knobs by `edge_coverage.jl`: 65 specializations covered by the edge
# walk, 74 that only observation can supply. The split by feature:
#
#   observation only   F2 `step` (12, K=12 subtypes), F4 `apply` (8, U=8
#                      members), F7 `collect_params` (12, a `Type{T}` dispatch)
#   edge walk covers   F3 `build_conn`/`count_set`, F5 `build_event`/
#                      `event_sum`/`pick_param`, F6 `node_address`, F8
#                      `format_value`, F9 `parse_config`, and the `site` calls
#
# `_scalar2` lands on the covered side because V=4 sits exactly AT the limit,
# and `_scalar` splits under its caller. Keep K, U and V straddling the limit:
# lower them all below 4 and the program stops testing half the design.

const A = length(ARGS) >= 2 ? map(x -> parse(Int, x), ARGS[2:end]) : Int[]
g(i, d) = length(A) >= i ? A[i] : d
const K = g(1, 12)   # F1/F2  concrete subtypes
const S = g(2, 40)   # F2     dynamic call sites
const N = g(3, 8)    # F3     optional fields, 2^N at the constructor
const U = g(4, 8)    # F4     union width, U^2 at the operator
const P = g(5, 4)    # F5     union-typed constructor parameters
const V = g(6, 4)    # F5     members per parameter, V^P at the constructor

# FEATURES_TRACE=1 makes every generated method announce itself and the
# concrete type it ran on. Running the trimmed binary then yields the set of
# specializations the program ACTUALLY executes — the ground truth the compiled
# list must be judged against. Only this program's own methods are tagged; they
# are generated here, so the tags can not disturb anything else.
const TR = get(ENV, "FEATURES_TRACE", "") != ""

function emit(k, s, n, u, p, v)
    io = IOBuffer()
    w(x...) = println(io, x...)
    # `tr(...)` emits a trace line, or nothing when tracing is off.
    tr(what, args = "") = TR ? w("    _trace(\"", what, "\"", args, ")") : nothing

    w("# GENERATED by features.jl — K=$k S=$s N=$n U=$u P=$p V=$v")
    w()
    w("# --- F1: an abstract type and its concretes -------------------------")
    w("abstract type Node end")
    for i in 1:k
        w("struct T$i <: Node; v::Int; end")
    end
    if TR
        w()
        w("# STOCK-RUN ONLY. Prints the executing method and the concrete types")
        w("# of its arguments, so a line is directly comparable to a compiled")
        w("# signature. Never built into a trimmed binary.")
        w("function _trace(name, args...)")
        w("    print(Core.stdout, \"TRACE \", name, \"(\")")
        w("    for (i, a) in enumerate(args)")
        w("        i > 1 && print(Core.stdout, \", \")")
        w("        # A TYPE-valued argument dispatches on `Type{T}`, not on")
        w("        # `typeof(it)`, which is merely DataType. Recording the")
        w("        # latter loses the dispatch and a trace-driven build then")
        w("        # has no entry for `collect_params(::Type{T1})`.")
        w("        print(Core.stdout, a isa Type ? string(\"Type{\", a, \"}\") : typeof(a))")
        w("    end")
        w("    println(Core.stdout, \")\")")
        w("end")
    end
    w()
    w("# --- F2: dynamic dispatch, one method per concrete type -------------")
    for i in 1:k
        if TR
            w("Base.@noinline function step(x::T$i)::Int"); tr("step", ", x"); w("    x.v + $i"); w("end")
        else
            w("Base.@noinline step(x::T$i)::Int = x.v + $i")
        end
    end
    # Each site takes the ABSTRACT type, so each is its own declined split.
    for j in 1:s
        if TR
            w("Base.@noinline function site$j(x::Node)::Int"); tr("site$j", ", x"); w("    step(x) + $j"); w("end")
        else
            w("Base.@noinline site$j(x::Node)::Int = step(x) + $j")
        end
    end
    w()
    w("# --- F6: a STEM instance — one body serves every layout -------------")
    if TR
        w("Base.@noinline function node_address(@nospecialize(x::Node))::Int")
        tr("node_address", ", x"); w("    getfield(x, 1)::Int"); w("end")
    else
        w("Base.@noinline node_address(@nospecialize(x::Node))::Int = getfield(x, 1)::Int")
    end
    w()
    w("# --- F7: generated per-type methods, one instance per kind ----------")
    for i in 1:k
        if TR
            w("function collect_params(::Type{T$i})::Int"); tr("collect_params", ", T$i"); w("    $i * 10"); w("end")
        else
            w("collect_params(::Type{T$i})::Int = $i * 10")
        end
    end
    w()
    w("# --- F3: a record of $n optional fields -----------------------------")
    w("struct Conn")
    for i in 1:n
        w("    f$i::Union{Nothing,String}")
    end
    w("end")
    w("Base.@noinline function build_conn(i::Int, a::String)")
    tr("build_conn", ", i, a")
    for i in 1:n
        w("    f$i = isodd(i + $i) ? a : nothing")
    end
    w("    Conn(", join(("f$i" for i in 1:n), ", "), ")")
    w("end")
    # `a + b + c` parses as ONE n-ary `+`, which lowers to a varargs splat
    # through `afoldl` — a call the trim cannot resolve. Explicit pairing keeps
    # every addition binary.
    let acc = "(c.f1 === nothing ? 0 : 1)"
        for i in 2:n
            acc = "($acc + (c.f$i === nothing ? 0 : 1))"
        end
        w("Base.@noinline count_set(c::Conn)::Int = ", acc)
    end
    w()
    w("# --- F4: a binary operator over a $u-member union -------------------")
    w("struct Q$(1)x; q::Int; end")
    members = ["Int64", "Float64", "String", "Bool", "Char", "UInt8", "Int32", "Q1x"]
    umembers = members[1:min(u, length(members))]
    w("const Value = Union{", join(umembers, ", "), "}")
    if TR
        w("Base.@noinline function apply(a::Value, b::Value)::Int")
        w("    _trace(\"apply\", a, b)")
        w("    _scalar(a) + _scalar(b)"); w("end")
    else
        w("Base.@noinline apply(a::Value, b::Value)::Int = _scalar(a) + _scalar(b)")
    end
    if TR
        w("function _scalar(x::Int64)::Int"); tr("_scalar", ", x"); w("    x"); w("end")
    else
        w("_scalar(x::Int64)::Int = x")
    end
    if TR
        w("function _scalar(x::Float64)::Int"); tr("_scalar", ", x"); w("    Int(round(x))"); w("end")
    else
        w("_scalar(x::Float64)::Int = Int(round(x))")
    end
    if TR
        w("function _scalar(x::String)::Int"); tr("_scalar", ", x"); w("    length(x)"); w("end")
    else
        w("_scalar(x::String)::Int = length(x)")
    end
    if TR
        w("function _scalar(x::Bool)::Int"); tr("_scalar", ", x"); w("    x ? 1 : 0"); w("end")
    else
        w("_scalar(x::Bool)::Int = x ? 1 : 0")
    end
    if TR
        w("function _scalar(x::Char)::Int"); tr("_scalar", ", x"); w("    Int(x) % 97"); w("end")
    else
        w("_scalar(x::Char)::Int = Int(x) % 97")
    end
    if TR
        w("function _scalar(x::UInt8)::Int"); tr("_scalar", ", x"); w("    Int(x)"); w("end")
    else
        w("_scalar(x::UInt8)::Int = Int(x)")
    end
    if TR
        w("function _scalar(x::Int32)::Int"); tr("_scalar", ", x"); w("    Int(x)"); w("end")
    else
        w("_scalar(x::Int32)::Int = Int(x)")
    end
    if TR
        w("function _scalar(x::Q1x)::Int"); tr("_scalar", ", x"); w("    x.q"); w("end")
    else
        w("_scalar(x::Q1x)::Int = x.q")
    end
    w("Base.@noinline function pick_value(i::Int)::Value")
    for (idx, m) in enumerate(umembers)
        lit = Dict("Int64" => "i", "Float64" => "Float64(i)", "String" => "\"s\"",
                   "Bool" => "isodd(i)", "Char" => "'a'", "UInt8" => "UInt8(i % 256)",
                   "Int32" => "Int32(i)", "Q1x" => "Q1x(i)")[m]
        w("    ", idx == 1 ? "if" : "elseif", " i % $(length(umembers)) == $(idx - 1)")
        w("        return ", lit)
    end
    w("    end")
    w("    return 0")
    w("end")
    w()
    w("# --- F5: a parametric constructor over $p union parameters ----------")
    vmembers = ["Int64", "Float64", "Bool", "Char", "UInt8"][1:min(v, 5)]
    w("const Param = Union{", join(vmembers, ", "), "}")
    w("struct Event{T}")
    w("    tag::T")
    for i in 1:p
        w("    p$i::Param")
    end
    w("end")
    w("Base.@noinline function build_event(i::Int)")
    tr("build_event", ", i")
    for i in 1:p
        w("    q$i = pick_param(i + $i)")
    end
    w("    Event(i, ", join(("q$i" for i in 1:p), ", "), ")")
    w("end")
    w("Base.@noinline function pick_param(i::Int)::Param")
    for (idx, m) in enumerate(vmembers)
        lit = Dict("Int64" => "i", "Float64" => "Float64(i)", "Bool" => "isodd(i)",
                   "Char" => "'b'", "UInt8" => "UInt8(i % 256)")[m]
        w("    ", idx == 1 ? "if" : "elseif", " i % $(length(vmembers)) == $(idx - 1)")
        w("        return ", lit)
    end
    w("    end")
    w("    return 0")
    w("end")
    w("Base.@noinline event_sum(e::Event)::Int = _scalar2(e.p1)")
    if TR
        w("function _scalar2(x::Int64)::Int"); tr("_scalar2", ", x"); w("    x"); w("end")
    else
        w("_scalar2(x::Int64)::Int = x")
    end
    if TR
        w("function _scalar2(x::Float64)::Int"); tr("_scalar2", ", x"); w("    Int(round(x))"); w("end")
    else
        w("_scalar2(x::Float64)::Int = Int(round(x))")
    end
    if TR
        w("function _scalar2(x::Bool)::Int"); tr("_scalar2", ", x"); w("    x ? 1 : 0"); w("end")
    else
        w("_scalar2(x::Bool)::Int = x ? 1 : 0")
    end
    if TR
        w("function _scalar2(x::Char)::Int"); tr("_scalar2", ", x"); w("    Int(x) % 98"); w("end")
    else
        w("_scalar2(x::Char)::Int = Int(x) % 98")
    end
    if TR
        w("function _scalar2(x::UInt8)::Int"); tr("_scalar2", ", x"); w("    Int(x)"); w("end")
    else
        w("_scalar2(x::UInt8)::Int = Int(x)")
    end
    w()
    w("# --- F8: keyword arguments ------------------------------------------")
    w("Base.@noinline function format_value(v::Int; width::Int = 4, pad::Char = '0', sign::Bool = false)")
    w("    s = string(v)")
    w("    while length(s) < width; s = pad * s; end")
    w("    sign && v >= 0 ? \"+\" * s : s")
    w("end")
    w()
    w("# --- F9: run-time parsing and formatted output ----------------------")
    w("Base.@noinline function parse_config(text::String)::Int")
    tr("parse_config", ", text")
    w("    total = 0")
    w("    for part in split(text, ',')")
    w("        kv = split(part, '=')")
    w("        length(kv) == 2 || continue")
    w("        n = tryparse(Int, String(kv[2]))")
    w("        n === nothing || (total += n)")
    w("    end")
    w("    total")
    w("end")
    w()
    w("Base.@noinline function build_nodes()")
    w("    nodes = Vector{Node}(undef, $k)")
    for i in 1:k
        w("    nodes[$i] = T$i($i)")
    end
    w("    nodes")
    w("end")
    w()
    # The body both `warm` and `main` run, so the warm run mirrors the entry
    # phase by phase, exactly as a real build entry must.
    w("Base.@noinline function body(nodes::Vector{Node}, seed::Int)::Int")
    w("    total = 0")
    for j in 1:s
        w("    total += site$j(nodes[($j - 1) % $k + 1])")
    end
    w("    total += node_address(nodes[1]) % 7")
    w("    for i in 1:$k")
    # A dispatch on `Type{T}` cannot have its RETURN type inferred, so the sum
    # became `+(Any, Any)` and was itself unresolvable. Every method here
    # returns Int, so the call site states it. This is the program telling the
    # truth about itself, not a workaround for a compiler limit.
    w("        total += collect_params(typeof(nodes[i]))::Int")
    w("    end")
    w("    total += count_set(build_conn(seed, \"x\"))")
    w("    for i in seed:(seed + $(max(u, 4)))")
    w("        total += apply(pick_value(i), pick_value(i + 1))")
    w("    end")
    w("    for i in seed:(seed + $(max(v, 4)))")
    w("        total += event_sum(build_event(i))")
    w("    end")
    w("    total += length(format_value(total; width = 6, sign = true))")
    w("    total += parse_config(\"a=1,b=2,c=xyz\")")
    w("    total")
    w("end")
    w()
    w("function warm()")
    w("    body(build_nodes(), 1)")
    w("end")
    w()
    # THE PROTOCOL. The buildscript harvests `Method => specializations` right
    # after it includes this file, and a method has specializations only once
    # something has COMPILED it. The real entry therefore runs its warm phase
    # at include time; a file that merely defines `warm` hands the buildscript
    # an empty table, and the sealed dispatch machinery is never exercised.
    w("const __WARM_RESULT = warm()")
    w()
    w("function (@main)(argv::Vector{String})::Cint")
    w("    total = body(build_nodes(), length(argv) + 1)")
    w("    Base.print(Core.stdout, \"features total: \")")
    w("    Base.print(Core.stdout, total)")
    w("    Base.print(Core.stdout, \"\\n\")")
    w("    return Cint(0)")
    w("end")
    String(take!(io))
end

if length(ARGS) >= 1 && ARGS[1] == "source"
    print(emit(K, S, N, U, P, V))
end
