# Turn a RECORDED TRACE into a trim entry: the signatures the program actually
# executed become the entrypoint list.
#
#     julia trace_entry.jl <program.jl> <trace.txt> <out-entry.jl>
#
# WHY. The analysing compiler derives what to compile from types, and on the
# feature example it derived 580 signatures where the program executes 77 — the
# excess being `apply` over its union's 8x8 product and each `site` over all 12
# `Node` subtypes. A trace already NAMES the 77. Compiling exactly those needs
# no type analysis at all, so the build is the floor: the least compile time and
# the smallest binary any correct trim could reach for this program.
#
# It is a BASELINE, not a replacement. It is only correct for inputs that drive
# the same dispatch as the recorded run; a path the trace never took has no
# entry, and the binary would have nothing to call. That is precisely the
# question it exists to price.

const PROGRAM = ARGS[1]
const TRACE   = ARGS[2]
const OUT     = ARGS[3]

lines = filter(!isempty, strip.(readlines(TRACE)))
open(OUT, "w") do io
    println(io, "# GENERATED by trace_entry.jl from ", basename(TRACE), " — ",
                length(lines), " recorded signatures.")
    println(io, "# The trim compiles these and nothing derived from them.")
    println(io)
    println(io, "include(", repr(abspath(PROGRAM)), ")")
    println(io)
    n = 0
    for l in lines
        i = findfirst('(', l)
        i === nothing && continue
        name = l[1:i-1]
        args = strip(l[i+1:end-1])
        # `f()` has no argument types; the tuple must still be well formed.
        tup = isempty(args) ? "()" : "(" * args * (occursin(",", args) ? "" : ",") * ")"
        println(io, "Base.Experimental.entrypoint(", name, ", ", tup, ")")
        n += 1
    end
    println(io)
    println(io, "# `main` stays the program entry; the buildscript registers it.")
    println(stderr, "wrote ", n, " entrypoints to ", OUT)
end
