# The union PRODUCT blow-up, in the smallest program that shows it.
#
#     julia union_product.jl source 10 > work/product10.jl
#     ./product.sh 4 8 10 12 14
#
# WHAT IT MODELS. `NedConnection` is a record with ten optional strings — a
# faithful model of a NED connection, which really does have ten optional
# strings. Nothing about it is careless. Building one costs 2^10 = 1024
# union-split combinations at the constructor, and that is the third largest
# call site in a sealed routing build (DESIGN.md §8a).
#
# WHAT BLOWS UP. A call site costs the PRODUCT of its arguments' union sizes,
# while that product stays at or below `max_union_splitting`. The sealed
# toolchain sets that limit to 20 000 — one constant serving two jobs, because
# `max_methods` genuinely needs 20 000 at an abstract call site. So a record
# with n optional fields is enumerated 2^n ways, one full method search each,
# until 2^n passes 20 000 and the compiler gives up and widens instead.
#
# Stock Julia's `max_union_splitting` is 4. It would not enumerate this at all.
#
# WHOSE FAULT. The program's model is honest, so the fix belongs in the
# compiler (DESIGN.md §8b). This file is the test that says whether the
# compiler fix worked, and `sealed.sh build` is the test that says the abstract
# type support it exists for still does.

const N = length(ARGS) >= 2 ? parse(Int, ARGS[2]) : 10
# The union WIDTH per field, so the boundary can be probed on combinations
# rather than on field count: width 3 over 2 fields is 9 combinations, where
# width 2 over 3 fields is 8.
const W = length(ARGS) >= 3 ? parse(Int, ARGS[3]) : 2

function emit_source(n::Int)
    member(w) = w == 2 ? "Union{Nothing,String}" : "Union{Nothing,String,Symbol}"
    fields = join(("    f$i::$(member(W))" for i in 1:n), "\n")
    args   = join(("f$i" for i in 1:n), ", ")
    # Each argument is `Union{Nothing,String}` at the call site — exactly what a
    # parser produces for an optional field, and exactly what the constructor
    # then has to be split over.
    reads  = W == 2 ?
        join(("    f$i = isodd(i + $i) ? a : nothing" for i in 1:n), "\n") :
        join(("    f$i = i % 3 == 0 ? a : (i % 3 == 1 ? nothing : :s)" for i in 1:n), "\n")
    """
    # GENERATED by union_product.jl — a record of $n optional strings.
    struct Rec
    $fields
    end

    # The constructor call below carries $n `Union{Nothing,String}` arguments,
    # so its split product is 2^$n = $(2^n).
    Base.@noinline function build(i::Int, a::String)
    $reads
        Rec($args)
    end

    Base.@noinline count_set(r::Rec) = $(join(("(r.f$i === nothing ? 0 : 1)" for i in 1:n), " + "))

    function (@main)(argv::Vector{String})::Cint
        total = 0
        for i in 1:3
            total += count_set(build(i, "x"))
        end
        Base.print(Core.stdout, "set fields: ")
        Base.print(Core.stdout, total)
        Base.print(Core.stdout, "\\n")
        return Cint(0)
    end
    """
end

if length(ARGS) >= 1 && ARGS[1] == "source"
    print(emit_source(N))
end
