# The VERIFIER's cost, in the smallest program that shows it.
#
#     julia verify_stress.jl source 40 300 > work/stress.jl
#
# WHAT IT MODELS. The union-product cases (`union_product.jl`) stress
# INFERENCE. This one stresses the trim VERIFIER, which is a different phase
# with a different cost, and until now no small case reached it: every case in
# the suite verifies in well under a second, so a verifier change could be
# measured only by a twenty-minute routing build.
#
# THE COST. For every DYNAMIC statement the sealed verifier searches the method
# table — `findall(atype, method_table; limit = 20 000)` — and then asks whether
# every matched method is compiled. So the phase costs
#
#     (number of dynamic statements) x (cost of one method table search)
#
# and the search cost grows with the number of methods that match. The two
# arguments are exactly those two knobs:
#
#     K   concrete types, hence K methods of `step` for a search to match
#     S   distinct call sites, hence S dynamic statements to verify
#
# A routing build has roughly 60 000 compiled instances behind those statements.
# K=40 S=300 reaches the same phase in about a minute.
#
# WHY EACH CALL SITE IS SEPARATE. One call site in a loop is ONE statement, and
# the verifier would walk it once. `Base.@noinline` on S generated functions is
# what turns the count of call sites into a count of statements.

const K = length(ARGS) >= 2 ? parse(Int, ARGS[2]) : 40
const S = length(ARGS) >= 3 ? parse(Int, ARGS[3]) : 300

function emit_source(k::Int, s::Int)
    types = join(("struct T$i <: Node; v::Int; end" for i in 1:k), "\n")
    # One `step` method per concrete type: the method table search at a call
    # site typed by the ABSTRACT type matches all k of them.
    steps = join(("Base.@noinline step(x::T$i) = x.v + $i" for i in 1:k), "\n")
    # S separate call sites. Each takes the abstract type, so each is a dynamic
    # statement the verifier must check on its own.
    sites = join(("Base.@noinline site$j(x::Node) = step(x) + $j" for j in 1:s), "\n")
    calls = join(("    total += site$j(nodes[($j - 1) % $k + 1])" for j in 1:s), "\n")
    # Filled by assignment, NOT by a `Node[...]` literal: a literal of k
    # elements lowers to a k-way splat through `_apply_iterate`, which the trim
    # refuses on its own and which has nothing to do with the verifier cost
    # this case measures.
    ctors = join(("    nodes[$i] = T$i($i)" for i in 1:k), "\n")
    """
    # GENERATED by verify_stress.jl — $k types, $s dynamic call sites.
    abstract type Node end
    $types

    $steps

    $sites

    function (@main)(argv::Vector{String})::Cint
        nodes = Vector{Node}(undef, $k)
    $ctors
        total = 0
    $calls
        Base.print(Core.stdout, "total: ")
        Base.print(Core.stdout, total)
        Base.print(Core.stdout, "\\n")
        return Cint(0)
    end
    """
end

if length(ARGS) >= 1 && ARGS[1] == "source"
    print(emit_source(K, S))
end
